excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://markandrewj.github.io
title: ScratchPad
tagline: A log of interesting findings.
description: A log of interesting findings.
paginate: 5
