excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://markandrewj.github.io
title: A log of interesting findings.
tagline: A log of interesting findings.
description: My awesome new site
paginate: 5
